name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install GPG2
        run: sudo apt install gnupg2

      - name: Write private key
        run: echo -n ${{ secrets.GPG_PRIVATE }} | base64 -d >> private.gpg

      - name: Import private key
        run: gpg2 --allow-secret-key-import --import private.gpg

      - name: Build with Gradle
        run: ./gradlew build
        env:
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}

      - name: Release Build
        if: startsWith(github.ref, 'refs/tags/v')
        run: ./gradlew publishToSonatype closeAndReleaseRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}